### ISSUE TITLE
Cropped Image Sources

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#1]
Currently using [Gatherer Extractor](http://www.mtgsalvation.com/forums/magic-fundamentals/digital-magic-and-mtg-software/337224-mtg-gatherer-extractor-v3-15a-database-pics) for Images.

Cropped images from Gatherer site only as magiccards.info card sizes don't work with crop function.

**Comment by lodici** [comment]
Even images without the cropped artwork will be more than playable and in fact should be the final death knell of TextMode.

**Comment by ShawnieBoy** [comment]
![](http://www.gifbin.com/bin/25yuswsw28295.gif)

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#1
