### ISSUE TITLE
Integration Test

### ISSUE THREAD

**Issue by lodici** [magarena/magarenaCardBuilder#13]
I did a little integration test with the code you have written so far (click image to watch full size)...
![cardbuilder](https://cloud.githubusercontent.com/assets/2443519/7261902/38cc1522-e86d-11e4-9186-996834bfa1d6.gif)
I did not touch any of your code except to repoint to the new resources location. I placed all your code into new ``cardbuilder`` packages so they are separate from Magarena stuff and added a slightly adapted copy of the Cards Explorer screen. You can still run your CardMain class directly but now you have the option of seeing how it behaves in "real life".

Because of the all the resources it is probably best not to update the main repo but if you are interested I can create a fork and update it with these changes.

**Comment by ShawnieBoy** [comment]
Cool

I'd be interested to see what changes were made to integrate the resources - would give me a better place for testing layout than CardMain.

**Comment by ShawnieBoy** [comment]
Already see text needs to be sorted out, lol

**Comment by lodici** [comment]
I think the text corruption seems to be related to the frame color. Subsequent cards of the same color frame overwrite the previous image. You probably need to keep a clean copy of the frame which you restore before drawing each card. You would never have known this just using CardMain! I will create a fork.

**Comment by ShawnieBoy** [comment]
Yes, good point - It's just overwriting each time.

**Comment by lodici** [comment]
But even at this early stage you have got the frames, colors, names, cost, P/T - just about everything required to make the card image playable (even without the artwork). And we do not have to do any other updates to Magarena. That is a big win I say. 

BTW, you should come up with a Magarena watermark as a default crop image.

**Comment by ShawnieBoy** [comment]
Ahh, yes - good idea. And also we can now use the Morph overlay cards as well:

![Morph Overlay](http://media.wizards.com/images/magic/tcg/products/ktk/7uhasdf2usnhz/en_01_sldjkfhkdf.jpg)

**Comment by ShawnieBoy** [comment]
Once I've done token frames...

**Comment by ShawnieBoy** [comment]
I'm assuming this is the fork? https://github.com/lodici/magarena-cardbuilder
No pushed changes as yet :grin:

**Comment by lodici** [comment]
Yes that is the one. Sorry for the delay - first it took 45 mins to download the fork (approx 300M) and now I am having trouble getting it to run in netbeans. I think I am almost there but you might as well clone the fork and see if you can get it running.

**Comment by ShawnieBoy** [comment]
Oh sorry, thought you may had just forgot to push - I've got the fork, just there's no modifications to it compared to Magarena Normal

**Comment by lodici** [comment]
Can you get it to run ok?

**Comment by ShawnieBoy** [comment]
Yes

**Comment by ShawnieBoy** [comment]
The problem may be with a libpng warning on load? apparently a 'known incorrect sRGB profile', but not preventing me from launching

**Comment by lodici** [comment]
Wierd but it is related to groovy. When I use 2.4.1 as downloaded by ant into the release folder I get 
```
Exception from controller.runGame: Could not initialize class magic.data.CardDefinitions
java.lang.NoClassDefFoundError: Could not initialize class magic.data.CardDefinitions
	at magic.utility.MagicSystem$2.run(MagicSystem.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
I referenced groovy 2.3.4 instead and it works fine. 

Anyway, I can sort those updates now.

**Comment by ShawnieBoy** [comment]
Weird...

Thanks

**Comment by lodici** [comment]
Ok updates published. All your classes can be found in ``magic.cardbuilder``. I have added a slightly adapted version of the Card Explorer screen, the classes of which can be found in ``magic.cardbuilder.ui``. The code you will probably be most interested in is [``setCard``](https://github.com/lodici/magarena-cardbuilder/blob/master/src/magic/cardbuilder/ui/CardBuilderViewer.java#L124.)  When you select a card in the explorer the associated MagicCardDefinition is passed to ``setCard``. I updated this based on your code in CardMain to call CardBuilder with the MagicCardDefinition (not keen on the use of MagicCard BTW :wink). You can still call your CardMain if would prefer not to run the whole Magarena app.

**Comment by ShawnieBoy** [comment]
Excellent thanks for doing that - already looking at it now

**Comment by ShawnieBoy** [comment]
MagicCard will need to be there for in-game rendering, and being able to create a psuedoCard from a MagicCardDefinition will prevent having to have different references.

**Comment by lodici** [comment]
But for out-of-game images you should only need a public API that accepts MagicCardDefinition because basically MagicCard does not exist outside of a MagicDuel. Having a different call for in-game that accepts MagicCard would be much clearer.

**Comment by ShawnieBoy** [comment]
I've currently got two: createCard(MagicCard) and createCard(MagicCardDefinition)

The MagicCardDefinition creates a MagicCard and calls createCard(MagicCard)

**Comment by lodici** [comment]
Ah, I think your last two commits did not make it to the fork. Sorry. That's fine then - how you implement stuff is entirely up to you but as far as Magarena is concerned it would not expect to pass a MagicCard to CardBuilder unless a duel is in progress.

**Comment by ShawnieBoy** [comment]
My bad as well - it got kinda absorbed into a different commit.

Agreed - I can fiddle with the rest here. Fun times

**Comment by lodici** [comment]
Great, I will leave you to it.

**Comment by ShawnieBoy** [comment]
Will try not to confuse myself and start pushing from the wrong repository

**Comment by ShawnieBoy** [comment]
I've already decided to physically remove the cardbuilder files from the integrated version and refer to them via my project instead - saves duplicate files and confusion :grinning:

**Comment by lodici** [comment]
@ShawnieBoy here is a typical error when trying to view a missing image in the CardBuilderScreen...
```
magic.exception.ScriptParseException: unknown ability "Enchant creature"
magic.model.MagicAbility.getAbility(MagicAbility.java:1384)
magic.data.CardProperty$13.setProperty(CardProperty.java:95)
magic.model.MagicCardDefinition.loadAbilities(MagicCardDefinition.java:179)
magic.model.MagicCard.<init>(MagicCard.java:94)
magic.model.MagicCard.<init>(MagicCard.java:82)
magic.cardbuilder.CardReader.createCard(CardReader.java:37)
magic.cardbuilder.ui.CardBuilderViewer.setCard(CardBuilderViewer.java:126)
magic.cardbuilder.ui.CardBuilderViewer.setCard(CardBuilderViewer.java:140)
```
I think it is because it trying to do "in-game" initializiation (via MagicCard -> loadAbilities?) for each selected card when it should only need a much lighter "out-of-game"  init for displaying the basic card properties. 

Is there anything required for displaying the basic card properties that you cannot get from MagicCardDefinition?

**Comment by lodici** [comment]
@ShawnieBoy please can you check that you are able to refresh your local copy of magarena-cardbuilder with the latest updates. I have been trying to work out how to keep the forked repo in-sync with the main repo and I think I have finally found the solution but I just want to make sure it does not affect other local repo's. Thanks.

**Comment by lodici** [comment]
@ShawnieBoy please can you check that you are able to refresh your local copy of magarena-cardbuilder with the latest updates. I have been trying to work out how to keep the forked repo in-sync with the main repo and I think I have finally found the solution but I just want to make sure it does not affect other local repo's. Thanks.

**Comment by lodici** [comment]
@ShawnieBoy please can you check that you are able to refresh your local copy of magarena-cardbuilder with the latest updates. I have been trying to work out how to keep the forked repo in-sync with the main repo and I think I have finally found the solution but I just want to make sure it does not affect other local repo's. Thanks.

**Comment by ShawnieBoy** [comment]
>Is there anything required for displaying the basic card image that you cannot get from MagicCardDefinition?

Grr, I was hoping to be able to be able to keep one system for creating an image. I think the suggestion by @melvinzhang in #5 of a 'MagicRenderable' makes more sense now.

I'll have a look at the differing methods once I get in-text images sorted.

**Comment by ShawnieBoy** [comment]
@lodici All seems fine with the repo - Does that mean I can push to the cardBuilder and the fork will pull it?

**Comment by lodici** [comment]
> @lodici All seems fine with the repo - Does that mean I can push to the cardBuilder and the fork will pull it?

Unfortunately not. I would humbly suggest you start using the fork for development from now on. Consider the ``cardmain.*`` packages (in ``src`` and ``resources``) your domain and the equivalent of this standalone CardBuilder project. You can still experiment and try stuff out using CardMain but now you can easily run Magarena to test and develop against real data as well. And you have access to the full Magarena source which we can keep up to date with the main repo. And myself and @melvinzhang (or anyone else) can have a play or help out if required. And finally, it should mean much less work the when the time comes [to merge into the main repo](https://github.com/magarena/magarena/compare/master...lodici:master).

II would also like to move the fork into the Magarena project now that @melvinzhang has given us the permissions since it seems a more appropriate place. I am not quite sure of the procedure but it might mean holding off on updating the fork for a while until it is up and running and then re-pointing your git remote.

**Comment by ShawnieBoy** [comment]
I moved mine with no issue - I'm unsure how to go about merging the issues into your fork

**Comment by lodici** [comment]
> I moved mine with no issue - I'm unsure how to go about merging the issues into your fork

Forks might not be so easy. I await @melvinzhang's advice.

**Comment by ShawnieBoy** [comment]
I've just experimented with pushing over the top >.<

**Comment by lodici** [comment]
"pushing over the top"?

**Comment by ShawnieBoy** [comment]
magarenaCardBuilder exists - pushing your fork to the cardBuilder, keep the issues and then remove my cardbuilder

**Comment by ShawnieBoy** [comment]
Essentially pushing a branch and then 'pruning'?

**Comment by ShawnieBoy** [comment]
Sounds so wrong...

**Comment by lodici** [comment]
> magarenaCardBuilder exists - pushing your fork to the cardBuilder, keep the issues and then remove my cardbuilder

The fork has the main magarena repo as its baseline which is how it is able to compare and display
![screenshot00118](https://cloud.githubusercontent.com/assets/2443519/7285868/c911e1d4-e93f-11e4-8e41-6606bbd0d8f4.png)
and offer the chance to merge with a [pull request](https://github.com/magarena/magarena/compare/master...lodici:master).

Pushing the fork would not include all the GitHub jiggery-pokery that makes a fork a fork. I would imagine.

**Comment by lodici** [comment]
The alternative, to revisist an old topic, is to create a CardBuilder branch in the main repo which you can work on.

**Comment by melvinzhang** [comment]
@lodici responding to the tag, is the issue of fork/branch resolved?

**Comment by ShawnieBoy** [comment]
We're all owners.

**Comment by lodici** [comment]
I does not seem to allow you to create a fork of a repository into the same account that owns the repository. I think we will just have stick with the ``lodici\magarena-cardbuilder`` repo. I will try to remember not to delete it!

**Comment by lodici** [comment]
> We're all owners.

I'm not.

_python..._

**Comment by ShawnieBoy** [comment]
What about a branch then?

**Comment by ShawnieBoy** [comment]
Oh, I was referring to this repository - we all own this part and can move it where needed

**Comment by melvinzhang** [comment]
@lodici can you try the transfer ownership method I suggested on the mailing list

**Comment by lodici** [comment]
> @lodici can you try the transfer ownership method I suggested on the mailing list

Will do, did not realize there was a post (might have got lost in @ShawnieBoy's issue transfer notifications!).

**Comment by lodici** [comment]
Done.

**Comment by melvinzhang** [comment]
Errm, I mean transfer to the org not to me.. Seems that I can't transfer it into the org, since github has something against a repo and its fork under the same owner. Transferring it back to you.

**Comment by lodici** [comment]
Lol! So I transfer to "magarena"?

**Comment by melvinzhang** [comment]
Yes, that's what I tried to do, but it failed saying that the org already has a repo in the network, where a network is a repo and all its forks.

**Comment by lodici** [comment]
![screenshot00124](https://cloud.githubusercontent.com/assets/2443519/7289962/88679342-e96f-11e4-8307-e415a4955e29.png)
Looks like it will have to stays where it is.
