### ISSUE TITLE
Tap, Untap and Snow Icons

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#17]
Currently the Tap and Untap symbols are held in MagicIcon and are grouped with the mana icons due to being on the Mana.png.

However they are unable to be obtained, as the IconImages determines them to be mana and tries to obtain a ManaIcon - and fails as they do not have a ManaType.

A similar issue with the Snow Icon, but that is understandable as Snow mana isn't implemented yet.

**Comment by lodici** [comment]
Are you saying that [``getIcon``](https://github.com/lodici/magarena-cardbuilder/blob/master/src/magic/ui/IconImages.java#L41) is not returning the tap/untap icons? Can you point me to the code you are using.

**Comment by ShawnieBoy** [comment]
ImageBuilder.getIcon()

```java
private static ImageIcon getIcon(final String string){
        if (string=="{T}"){
            return IconImages.getIcon(MagicIcon.MANA_TAP);
        }
        else if (string=="{Q}"){
            return IconImages.getIcon(MagicIcon.MANA_UNTAP);
        }
        else if (string=="{S}"){
            return IconImages.getIcon(MagicIcon.MANA_SNOW);
        } else {
            final MagicManaType mana = MagicManaType.get(string);
            return IconImages.getIcon(mana);
        }
    }
```

**Comment by lodici** [comment]
Try ``string.equals("{T}")`` instead. Same for Q and S.

**Comment by lodici** [comment]
However, ``Abomination of Gudul`` generates
```
java.lang.RuntimeException: unknown mana type "{2}"
magic.model.MagicManaType.get(MagicManaType.java:51)
magic.cardbuilder.ImageBuilder.getIcon(ImageBuilder.java:236)
magic.cardbuilder.ImageBuilder.textIconReplace(ImageBuilder.java:251)
magic.cardbuilder.ImageBuilder.buildCard(ImageBuilder.java:78)
magic.cardbuilder.CardReader.createCard(CardReader.java:33)
magic.cardbuilder.CardReader.createCard(CardReader.java:37)
```
which is understandable since there is no such MagicManaType.

**Comment by ShawnieBoy** [comment]
I'll be getting to multiple-colorless-mana later

**Comment by ShawnieBoy** [comment]
Oh, see what you mean - that's strange

**Comment by lodici** [comment]
> That {1} works.

Well yes, that is a valid MagicManaType.
```
public enum MagicManaType {

    Colorless("colorless","{1}"),
    Black("black","{B}"),
    Blue("blue","{U}"),
    Green("green","{G}"),
    Red("red","{R}"),
    White("white","{W}"),
    NONE("none","{N}"),
    ;
```

**Comment by ShawnieBoy** [comment]
Making a manaCost then getting the icons is probably the best way. Save duplicating code

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#17
