### ISSUE TITLE
Add new issues to magarena-cardbuilder repo.

### ISSUE THREAD

**Issue by lodici** [magarena/magarenaCardBuilder#18]
Since development is now on the the forked repo it makes sense to post new issues to it. Although would be useful to hear from @melvinzhang whether it will be possible to move the fork first.

**Comment by ShawnieBoy** [comment]
doh!

**Comment by ShawnieBoy** [comment]
Just found an issue-mover, will see how it goes.

**Comment by lodici** [comment]
There is always something out there that does the thing you didn't think could be done!

**Comment by ShawnieBoy** [comment]
Looks like it worked on the first one - will do the rest :grinning:

**Comment by ShawnieBoy** [comment]
and hit a crash :cry:

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#18
