### ISSUE TITLE
completing card builder integration into main repo

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarenaCardBuilder#21]
Card builder has been integrated into the main repo and new development takes place there. Should any of the things in this repo (issues, wiki, etc) here be moved over? @ShawnieBoy

**Comment by ShawnieBoy** [comment]
No - I think this repo can be safely removed. I will have a look at my local copy and upload any .psd files that may be useful to push to Magarena for source-image reasons

**Comment by melvinzhang** [comment]
@ShawnieBoy ok, I'll remove this repo. On the psd files please hold on to them first, I think pushing them all into the main repo may not be the best idea. I'll look into how to best handle binary files.
