### ISSUE TITLE
Text scaling and readability

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#6]
There will be issues with card text size and readability. Grabbing the two most verbose cards I could think of, we have:

![ice cauldron](https://cloud.githubusercontent.com/assets/2363180/7242703/de58d450-e7bc-11e4-9c42-7f3ca3fd80c7.png)
![illusionary mask](https://cloud.githubusercontent.com/assets/2363180/7242704/dfe4425a-e7bc-11e4-9145-f42410339c87.png)

I don't think there are any cards with more text (correct me if I'm wrong, and we're talking oracle here). However, for a nightmare scenario, image both of these in play with a [March of the Machines](http://magiccards.info/arc/en/6.html), [Hivestone](http://magiccards.info/ts/en/256.html) and a bunch of Slivers.

**Comment by ShawnieBoy** [comment]
Ok, being more gentle with the font scaling, I've got here - This is definitely the limit as far as text size goes! (In-text icons to come)

![ice cauldron](https://cloud.githubusercontent.com/assets/2363180/7244225/3f23262e-e7d0-11e4-8204-1008979caf91.png)
![illusionary mask](https://cloud.githubusercontent.com/assets/2363180/7244224/3f22ba40-e7d0-11e4-99b9-b2e6fe71c20c.png)

**Comment by melvinzhang** [comment]
There should some minimum size of the text for readability, if the text would go below that size, I think it is better to remove it and require the user to mouse over the card to see the full image with text.

**Comment by ShawnieBoy** [comment]
Yes, but these will be the full image with text...

**Comment by melvinzhang** [comment]
Oh, then I think the 3rd image is fairly readable. Having all the text run together as in the 2nd and 4th image makes it very hard to read.

**Comment by lodici** [comment]
I think these look great. Assuming these would be the original size (which is what BTW?) then you could hand this image to Magarena now and it would work like any of the current images, resizing, popup, etc. This is playable even without the artwork, goodbye textmode and 
![missing_card](https://cloud.githubusercontent.com/assets/2443519/7244435/4cd72cf4-e7d3-11e4-82e5-3f9ce6f4a700.png)

**Comment by ShawnieBoy** [comment]
>Oh, then I think the 3rd image is fairly readable. Having all the text run together as in the 2nd and 4th image makes it very hard to read.

They are two different cards, one has two abilities the other only one - hence the two blocks/one block of text.

> Assuming these would be the original size (which is what BTW?) then you could hand this image to Magarena now and it would work like any of the current images, resizing, popup, etc. 

These are 375x523

These would be spat out by cardBuilder as a BufferedImage, so yes.

**Comment by ShawnieBoy** [comment]
[Illusionary Mask](http://magiccards.info/cedi/en/251.html) The idiot child of MtG - poor thing.

I chose it as an extreme text case :grinning:

**Comment by ShawnieBoy** [comment]
While you're both here - I have a message up on the Groups forum.

**Comment by ShawnieBoy** [comment]
@lodici What method is used in the Card Explorer for displaying mana icons amongst text?

**Comment by ShawnieBoy** [comment]
lol, ignore that - I could have sworn there were

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#6
