### ISSUE TITLE
Enable in-text image placement for activated abilities

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#8]
Mana costs, tap/untap symbol, etc

**Comment by ShawnieBoy** [comment]
e9b84a6dfe3291daf5e123c36ece4ae2456d22e8 is a start, however a problem with immutable strings and AttributedString.

More and more of my code is becoming a complete mess, lol

**Comment by lodici** [comment]
Refactor, refactor and then refactor some more! :smile: 

Not a refactor but a hint - to center CardMain on the screen make sure 
```
mainFrame.setSize(392,689);
```
comes before
```
mainFrame.setLocationRelativeTo(null);
```

**Comment by ShawnieBoy** [comment]
Not really using cardMain anymore - The CardBuilder panel gives a better representation on what's going on - just a shame of the load-times

**Comment by lodici** [comment]
Yes I noticed a slight pause now and again. Not wanting to harp on about it but ... ``loadAbilities()``? There is a reason this is not called by default when starting Magarena. The images themselves are looking good though. I thought of adding the ability to let you swap between a CardBuilder image and the downloaded image which might be useful to compare fonts and stuff.

**Comment by ShawnieBoy** [comment]
>I thought of adding the ability to let you swap between a CardBuilder image and the downloaded image which might be useful to compare fonts and stuff.

Hehe, that would just make me sad at the moment - I'm really not happy with the font-rendering, and do wonder if it's just a java thing. Maybe the anti-aliasing is fudging with it, but with it off it looks even worse!

**Comment by lodici** [comment]
Just to give an example of a refactor using [``getFrameType()``](https://github.com/lodici/magarena-cardbuilder/blob/master/src/magic/cardbuilder/CardReader.java#L61).

In getFrameType() you are using ``MagicCard`` but if you dig down into the methods called they are delegated to ``MagicCardDefinition`` methods. ``MagicColor.isMulti()`` is a bit more problematic since it requires a ``MagicCard`` but again if you follow the code to ``numColors()``, what is it checking...``MagicCardDefinition``! This says to me that ``MagicColor.isMulti()`` should either be accepting a ``MagicCardDefinition`` directly or it should be overloaded to accept both a ``MagicCard`` or ``MagicCardDefinition`` object.

**Comment by lodici** [comment]
> I'm really not happy with the font-rendering, and do wonder if it's just a java thing. Maybe the anti-aliasing is fudging with it, but with it off it looks even worse!

You definitely need to use the anti-alias hints. Could it be the custom fonts? The "ey" and "el" do look a bit scrunched.
![screenshot00122](https://cloud.githubusercontent.com/assets/2443519/7287671/39f249a2-e94f-11e4-8003-4b17ede3fbc3.png)
![screenshot00119](https://cloud.githubusercontent.com/assets/2443519/7287638/b4880734-e94e-11e4-897c-2a4fa7d0a034.png)
![screenshot00120](https://cloud.githubusercontent.com/assets/2443519/7287663/0e4a9ac0-e94f-11e4-8085-9a8945b9ff88.png)
I would have to compare with the original to see the differences (oh, hang on... :wink:) .

**Comment by ShawnieBoy** [comment]
I think the MagicCard/MagicCardDefinition can be separated out later, My concern with code-mess is mainly around string manipulation - Still just want to be able to display a full card!

Could you have a look at #17?

**Comment by ShawnieBoy** [comment]
>You definitely need to use the anti-alias hints. Could it be the custom fonts? The "ey" and "el" do look a bit scrunched.

Quite possibly, though could just be kerning elsewhere

**Comment by lodici** [comment]
> Could you have a look at #17?

Assigned.

**Comment by lodici** [comment]
> just a shame of the load-times

I should point out that I removed image caching in ``CardBuildViewer.setCard()`` but I don't think it makes a huge difference in the explorer unless you are flicking back and forth across the same set of images. But I will add it back since it better reflects how the main repo works.

**Comment by ShawnieBoy** [comment]
With the immutability of AtrributedText I've managed to hack the removal of the curly-brackets with a 1 pixel empty, transparent image.

The only way I could work out a solution
